# Generated by Django 3.2.3 on 2021-07-14 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date assigned')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('pronouns', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('last_login', models.CharField(max_length=400)),
                ('location', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gad7FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gad7_response_q1', models.IntegerField()),
                ('gad7_response_q2', models.IntegerField()),
                ('gad7_response_q3', models.IntegerField()),
                ('gad7_response_q4', models.IntegerField()),
                ('gad7_response_q5', models.IntegerField()),
                ('gad7_response_q6', models.IntegerField()),
                ('gad7_response_q7', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('pronouns', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=500)),
                ('certification', models.CharField(max_length=150)),
                ('certnum', models.CharField(max_length=100)),
                ('last_login', models.CharField(max_length=400)),
                ('location', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hih.client')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hih.provider')),
            ],
        ),
    ]
