# Generated by Django 3.2.5 on 2021-07-15 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hih', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='client',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='client',
            name='location',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='certnum',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='email',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='location',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='phone',
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='provider',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='pronouns',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='pronouns',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
