# Generated by Django 3.2.3 on 2021-07-16 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hih', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gad7formresponse',
            old_name='client',
            new_name='client_id',
        ),
    ]
