# Generated by Django 3.2.3 on 2021-07-15 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hih', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='provider',
        ),
    ]
