# Generated by Django 3.2.3 on 2021-07-15 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hih', '0002_remove_photo_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='gad7formresponse',
            name='gad7_completion_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
