# Generated by Django 3.2.3 on 2021-07-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hih', '0002_auto_20210710_0532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
