# Generated by Django 3.2.5 on 2021-07-16 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hih', '0002_auto_20210715_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hih.provider'),
        ),
    ]
