# Generated by Django 3.2.3 on 2021-07-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hih', '0003_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='client',
            name='lastname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='lastname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
