# Generated by Django 3.2.3 on 2021-07-10 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hih', '0004_auto_20210710_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='user',
        ),
    ]
