# Generated by Django 3.2.3 on 2021-07-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hih', '0005_auto_20210710_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_login',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
