# Generated by Django 3.2.3 on 2021-07-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hih', '0006_client_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='last_login',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
