# Generated by Django 3.2.3 on 2021-07-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hih', '0007_provider_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
