# Generated by Django 3.2.3 on 2021-07-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hih', '0008_test2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gad7FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gad7_response_q1', models.IntegerField()),
                ('gad7_response_q2', models.IntegerField()),
                ('gad7_response_q3', models.IntegerField()),
                ('gad7_response_q4', models.IntegerField()),
                ('gad7_response_q5', models.IntegerField()),
                ('gad7_response_q6', models.IntegerField()),
                ('gad7_response_q7', models.IntegerField()),
            ],
        ),
    ]
