# Generated by Django 3.2.3 on 2021-07-13 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hih', '0008_test2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hih.client')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hih.provider')),
            ],
        ),
    ]
