# Generated by Django 3.2.3 on 2021-07-13 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hih', '0009_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='provider',
        ),
    ]
