# Generated by Django 3.2.3 on 2021-07-13 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hih', '0010_remove_photo_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hih.provider'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hih.client'),
        ),
    ]
